import esbuild from "esbuild";
import process, { exit } from "process";
import builtins from "builtin-modules";
import fs, { existsSync } from "fs";
import path from "path";
import chokidar from "chokidar";

async function loadPluginDir() {
  const configName = "carnelianrc.json";

  if (!existsSync(configName)) {
    console.error(`${configName}がカレントディレクトリに存在しません`);
    exit(1);
  }

  let rcConfig;
  try {
    rcConfig = await Bun.file(configName).json();
  } catch (e) {
    console.error(`${configName}のパースに失敗しました`);
    exit(1);
  }

  const vaultPath = rcConfig.vaultPath;
  if (!vaultPath) {
    console.error("carnelianrc.jsonにVaultのパスが指定されていません");
    exit(1);
  }
  if (!existsSync(vaultPath)) {
    console.error(
      `carnelianrc.jsonのVaultに指定されたパス ${vaultPath} は存在しません`,
    );
    exit(1);
  }

  return path.join(vaultPath, ".obsidian/plugins/carnelian");
}

const pluginDir = await loadPluginDir();

console.log(`📁 ${pluginDir}ディレクトリを作成します(既にある場合は変更なし)`);
fs.mkdirSync(pluginDir, { recursive: true });

const hotreloadPath = path.join(pluginDir, ".hotreload", "");
console.log(`🌶️ ${hotreloadPath}ファイルを作成します`);
fs.writeFileSync(hotreloadPath, "");

const FILES = ["main.js", "manifest.json", "styles.css"];

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();

  const watcher = chokidar.watch(FILES, { persistent: true });
  watcher
    .on("add", (p) => {
      fs.copyFileSync(p, path.join(pluginDir, p));
    })
    .on("change", (p) => {
      fs.copyFileSync(p, path.join(pluginDir, p));
    });
}
