import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";
import chokidar from "chokidar";

const PLUGIN_DIR =
  "/mnt/c/Users/syoum/work/minerva/.obsidian/plugins/obsidian-plugin-for-tadashi-aikawa/";
const FILES = ["main.js", "manifest.json", "styles.css"];

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();

  const watcher = chokidar.watch(FILES, { persistent: true });
  watcher
    .on("add", (p) => {
      fs.copyFileSync(p, path.join(PLUGIN_DIR, p));
    })
    .on("change", (p) => {
      fs.copyFileSync(p, path.join(PLUGIN_DIR, p));
    });
}
