import builtins from "builtin-modules";
import chokidar from "chokidar";
import esbuild from "esbuild";
import fs, { existsSync } from "fs";
import path from "path";
import process, { exit } from "process";

async function loadPluginDir() {
  const configName = "carnelianrc.json";

  if (!existsSync(configName)) {
    console.error(`${configName}がカレントディレクトリに存在しません`);
    exit(1);
  }

  let rcConfig;
  try {
    rcConfig = await Bun.file(configName).json();
  } catch (e) {
    console.error(`${configName}のパースに失敗しました`);
    exit(1);
  }

  const vaultPath = rcConfig.vaultPath;
  if (!vaultPath) {
    console.error("carnelianrc.jsonにVaultのパスが指定されていません");
    exit(1);
  }
  if (!existsSync(vaultPath)) {
    console.error(
      `carnelianrc.jsonのVaultに指定されたパス ${vaultPath} は存在しません`,
    );
    exit(1);
  }

  return path.join(vaultPath, ".obsidian/plugins/carnelian");
}

const pluginDir = await loadPluginDir();

console.log(`📁 ${pluginDir}ディレクトリを作成します(既にある場合は変更なし)`);
fs.mkdirSync(pluginDir, { recursive: true });

const hotreloadPath = path.join(pluginDir, ".hotreload", "");
console.log(`🌶 ${hotreloadPath}ファイルを作成します`);
fs.writeFileSync(hotreloadPath, "");

const FILES = ["main.js", "manifest.json", "styles.css", "config.schema.json"];
const CONFIG_DEFINITION_PATH = "src/definitions/config.ts";
const WATCH_FILES = [...FILES, CONFIG_DEFINITION_PATH];

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();

  const watcher = chokidar.watch(WATCH_FILES, {
    persistent: true,
    usePolling: true,
  });
  let schemaRunning = false;
  let schemaQueued = false;

  const runSchema = async () => {
    if (schemaRunning) {
      schemaQueued = true;
      return;
    }
    schemaRunning = true;

    try {
      console.log("♨  config.ts is changed -> run bun schema");
      const proc = Bun.spawn(["bun", "run", "schema"], {
        stdout: "inherit",
        stderr: "inherit",
      });
      const exitCode = await proc.exited;
      if (exitCode !== 0) {
        console.error(`bun schema failed (exit ${exitCode})`);
      }
    } catch (e) {
      console.error("bun schema failed", e);
    } finally {
      schemaRunning = false;
      if (schemaQueued) {
        schemaQueued = false;
        await runSchema();
      }
    }
  };

  const handleFileChange = (p) => {
    if (p === CONFIG_DEFINITION_PATH) {
      void runSchema();
      return;
    }

    if (!FILES.includes(p)) {
      return;
    }

    fs.copyFileSync(p, path.join(pluginDir, p));
  };
  watcher
    .on("add", (p) => {
      console.log(`♨  ${p} is added`);
      handleFileChange(p);
    })
    .on("change", (p) => {
      console.log(`♨  ${p} is changed`);
      handleFileChange(p);
    });
}
